unstable_features = true
hard_tabs = true
inline_attribute_width = 30
use_small_heuristics = "Max"
max_width = 90
reorder_imports = false
reorder_modules = false
reorder_impl_items = true
report_todo = "Always"
report_fixme = "Always"
struct_field_align_threshold = 25
use_field_init_shorthand = true
use_try_shorthand = true
match_arm_blocks = false
overflow_delimited_expr = true
edition = "2018"
